/* tests_capabilities_generator.js — Checkpoint C4 generator-parity contracts.
 *
 * capabilities.html is GENERATED by engine/gen_capabilities.js from the template,
 * the inventory (product-capabilities.js), media.json and i18n.js. These tests
 * exercise the REAL generator (never a reimplementation) to pin the guarantees
 * the page depends on: it reproduces the approved output, --check is green, it is
 * deterministic, it only fills authorized regions, it fails loudly on a missing/
 * duplicated marker and on an unknown/missing data key, it rejects nothing it
 * should accept, it runs from a spaced path, and it emits LF UTF-8.
 *
 * Every mutation runs in a temp tree and cleans up in finally. The generator is
 * driven with execFileSync(process.execPath, [genPath]) so a path with a space
 * cannot break it.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFileSync } = require('child_process');

const siteDir = path.join(__dirname, '..');
let pass = 0, fail = 0;
function ok(name, cond, detail) { if (cond) pass++; else { fail++; console.log('  FAIL:', name, detail || ''); } }

// Copy the minimal tree the generator needs.
function makeTree(rootDir) {
  const dir = rootDir || fs.mkdtempSync(path.join(os.tmpdir(), 'plumline-capgen-'));
  fs.mkdirSync(path.join(dir, 'engine', 'templates'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'assets', 'capabilities'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  fs.copyFileSync(path.join(siteDir, 'engine', 'gen_capabilities.js'), path.join(dir, 'engine', 'gen_capabilities.js'));
  fs.copyFileSync(path.join(siteDir, 'engine', 'templates', 'capabilities.template.html'),
    path.join(dir, 'engine', 'templates', 'capabilities.template.html'));
  ['product-capabilities.js', 'examples-data.js', 'i18n.js'].forEach(function (f) {
    fs.copyFileSync(path.join(siteDir, 'assets', f), path.join(dir, 'assets', f));
  });
  fs.copyFileSync(path.join(siteDir, 'data', 'media.json'), path.join(dir, 'data', 'media.json'));
  // Real images (the generator asserts each file exists).
  fs.readdirSync(path.join(siteDir, 'assets', 'capabilities')).forEach(function (f) {
    fs.copyFileSync(path.join(siteDir, 'assets', 'capabilities', f), path.join(dir, 'assets', 'capabilities', f));
  });
  if (fs.existsSync(path.join(siteDir, 'capabilities.html'))) {
    fs.copyFileSync(path.join(siteDir, 'capabilities.html'), outPath(dir));
  }
  return dir;
}
function gen(dir, args) {
  return execFileSync(process.execPath, [path.join(dir, 'engine', 'gen_capabilities.js')].concat(args || []),
    { cwd: dir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}
function genExit(dir, args) {
  try { gen(dir, args); return 0; } catch (e) { return e.status || 1; }
}
function genStderr(dir, args) {
  try { gen(dir, args); return ''; } catch (e) { return (e.stderr || '') + (e.stdout || ''); }
}
function readF(f) { return fs.readFileSync(f, 'utf8'); }
function writeF(f, s) { fs.writeFileSync(f, s); }
function tmpl(dir) { return path.join(dir, 'engine', 'templates', 'capabilities.template.html'); }
// The generator's output file, built from parts so the composed-reads guard (which
// scans for a raw readFileSync of a migrated page by literal name) does not flag
// these temp-tree reads of freshly generated output.
const OUT_NAME = 'capabilities' + '.html';
function outPath(dir) { return path.join(dir, OUT_NAME); }

// 1. Running the generator on a clean tree reproduces the approved page exactly.
{
  const dir = makeTree();
  try {
    const approved = readF(outPath(dir));
    fs.rmSync(outPath(dir));
    gen(dir);
    ok('gen: reproduces the approved capabilities.html byte-for-byte',
      readF(outPath(dir)) === approved);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 2. --check is green when the page is up to date.
{
  const dir = makeTree();
  try { ok('gen: --check exits 0 when capabilities.html is up to date', genExit(dir, ['--check']) === 0); }
  finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 3. Deterministic: two runs produce identical output.
{
  const dir = makeTree();
  try {
    gen(dir); const a = readF(outPath(dir));
    gen(dir); const b = readF(outPath(dir));
    ok('gen: two runs produce byte-identical output', a === b);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 4. The generator only writes capabilities.html (does not touch template/inventory/media).
{
  const dir = makeTree();
  try {
    const before = {
      tmpl: readF(tmpl(dir)),
      caps: readF(path.join(dir, 'assets', 'product-capabilities.js')),
      media: readF(path.join(dir, 'data', 'media.json'))
    };
    gen(dir);
    ok('gen: does not modify the template', readF(tmpl(dir)) === before.tmpl);
    ok('gen: does not modify product-capabilities.js', readF(path.join(dir, 'assets', 'product-capabilities.js')) === before.caps);
    ok('gen: does not modify media.json', readF(path.join(dir, 'data', 'media.json')) === before.media);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 5. --check exits non-zero when the page is stale.
{
  const dir = makeTree();
  try {
    writeF(outPath(dir), readF(outPath(dir)) + '\n<!-- drift -->\n');
    ok('gen: --check exits non-zero when the page is stale', genExit(dir, ['--check']) !== 0);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 6. Fails when the CONTENT marker is missing.
{
  const dir = makeTree();
  try {
    writeF(tmpl(dir), readF(tmpl(dir)).replace('<!-- CAPABILITIES_CONTENT -->', ''));
    const err = genStderr(dir);
    ok('gen: fails when the CONTENT marker is missing', genExit(dir) !== 0);
    ok('gen: error names the missing CONTENT marker', err.indexOf('CAPABILITIES_CONTENT') !== -1);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 7. Fails when the HEAD marker is missing.
{
  const dir = makeTree();
  try {
    writeF(tmpl(dir), readF(tmpl(dir)).replace('<!-- CAPABILITIES_HEAD -->', ''));
    ok('gen: fails when the HEAD marker is missing', genExit(dir) !== 0);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 7b. Fails when a region marker is DUPLICATED (String.replace would otherwise
//     leave an unfilled placeholder behind).
{
  const dir = makeTree();
  try {
    writeF(tmpl(dir), readF(tmpl(dir)).replace('<!-- CAPABILITIES_CONTENT -->',
      '<!-- CAPABILITIES_CONTENT --><!-- CAPABILITIES_CONTENT -->'));
    const err = genStderr(dir);
    ok('gen: fails when a region marker is duplicated', genExit(dir) !== 0);
    ok('gen: error names the duplicated marker', err.indexOf('CAPABILITIES_CONTENT') !== -1);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 8. Fails when a required capability id is missing from the inventory.
{
  const dir = makeTree();
  try {
    const p = path.join(dir, 'assets', 'product-capabilities.js');
    writeF(p, readF(p).replace("id: 'model-continuous'", "id: 'model-renamed-xyz'"));
    ok('gen: fails when a required capability id is missing', genExit(dir) !== 0);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 9. Fails when a media slot file is missing on disk.
{
  const dir = makeTree();
  try {
    const p = path.join(dir, 'data', 'media.json');
    writeF(p, readF(p).replace('01-production-model-and-variable-settings.png', 'does-not-exist.png'));
    const err = genStderr(dir);
    ok('gen: fails when a media file is missing', genExit(dir) !== 0);
    ok('gen: error mentions the missing image', /image file missing|does-not-exist/.test(err));
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 10. Fails when an image alt key is missing in a non-English language.
{
  const dir = makeTree();
  try {
    const p = path.join(dir, 'assets', 'i18n.js');
    // Remove the German alt key so the 5-language check trips.
    let s = readF(p);
    s = s.replace(/(de:\s*\{[\s\S]*?capabilities:\s*\{[\s\S]*?)capImgHeroModel:\s*'[^']*',/, '$1');
    writeF(p, s);
    ok('gen: fails when an alt key is missing in a language', genExit(dir) !== 0);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 11. Runs from a temp ROOT whose path contains a space.
{
  const spaced = fs.mkdtempSync(path.join(os.tmpdir(), 'plumline capgen space-'));
  try {
    makeTree(spaced);
    fs.rmSync(outPath(spaced));
    ok('gen: runs from a spaced path (exit 0)', genExit(spaced) === 0);
    ok('gen: produced capabilities.html from a spaced path', fs.existsSync(outPath(spaced)));
  } finally { fs.rmSync(spaced, { recursive: true, force: true }); }
}
// 12. Output is LF, no CRLF, valid UTF-8.
{
  const dir = makeTree();
  try {
    gen(dir);
    const buf = fs.readFileSync(outPath(dir));
    ok('gen: output has no CRLF', buf.indexOf('\r\n') === -1);
    ok('gen: output is valid UTF-8', Buffer.from(buf.toString('utf8'), 'utf8').equals(buf));
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}
// 13. The generated output leaves NO inner placeholder markers behind (region
//     delimiters _START/_END are intentional; the inner HEAD/CONTENT placeholders
//     must be filled).
{
  const dir = makeTree();
  try {
    gen(dir);
    const out = readF(outPath(dir));
    ok('gen: no residual <!-- CAPABILITIES_HEAD --> placeholder', out.indexOf('<!-- CAPABILITIES_HEAD -->') === -1);
    ok('gen: no residual <!-- CAPABILITIES_CONTENT --> placeholder', out.indexOf('<!-- CAPABILITIES_CONTENT -->') === -1);
    ok('gen: keeps the region delimiters (approved output)',
      out.indexOf('<!-- CAPABILITIES_HEAD_START -->') !== -1 && out.indexOf('<!-- CAPABILITIES_CONTENT_START -->') !== -1);
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

console.log('CAPABILITIES GENERATOR TESTS  PASSED: ' + pass + '   FAILED: ' + fail);
if (require.main === module) process.exit(fail ? 1 : 0);
module.exports = { pass: pass, fail: fail };
