/* tests_shell_golden.js — golden-baseline protection for the shared shell.
 *
 * The expected markup lives in engine/fixtures/shell-golden/*.html. Those fixtures
 * were extracted from the pre-B1 approved product (and, for the one case with no
 * real page — informational header with the solver link active — derived by hand
 * applying the known aria-current rule), NOT generated by calling the composer.
 * So if the composer drifts, the expected does NOT move with it: this suite fails.
 *
 * Each assertion composes a shell piece and compares byte-for-byte to its fixture.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const compose = require('../src/shared/compose-shell.js');

const DIR = path.join(__dirname, 'fixtures', 'shell-golden');
let pass = 0, fail = 0;
function eq(name, got, fixtureFile) {
  const want = fs.readFileSync(path.join(DIR, fixtureFile), 'utf8');
  if (got === want) { pass++; return; }
  fail++;
  // Show the first difference to make drift obvious.
  let i = 0; while (i < Math.min(got.length, want.length) && got[i] === want[i]) i++;
  console.log('  FAIL:', name, '(fixture ' + fixtureFile + ')');
  console.log('    got : ' + JSON.stringify(got.slice(Math.max(0, i - 20), i + 20)));
  console.log('    want: ' + JSON.stringify(want.slice(Math.max(0, i - 20), i + 20)));
}

// Headers.
eq('header informational, no active',       compose.renderHeader('informational', ''),         'header-informational-noactive.html');
eq('header informational, solver active',   compose.renderHeader('informational', 'solver'),   'header-informational-solver.html');
eq('header informational, guide active',    compose.renderHeader('informational', 'guide'),    'header-informational-guide.html');
eq('header informational, examples active', compose.renderHeader('informational', 'examples'), 'header-informational-examples.html');
eq('header informational, about active',    compose.renderHeader('informational', 'about'),    'header-informational-about.html');
eq('header solver',                         compose.renderHeader('solver', 'solver'),          'header-solver.html');

// Footers.
eq('footer informational (normal)',  compose.renderFooter('informational', false), 'footer-informational.html');
eq('footer capabilities (learn)',    compose.renderFooter('informational', true),  'footer-capabilities.html');
eq('footer solver',                  compose.renderFooter('solver', false),        'footer-solver.html');

console.log('SHELL GOLDEN TESTS  PASSED: ' + pass + '   FAILED: ' + fail);
if (require.main === module) process.exit(fail ? 1 : 0);
module.exports = { pass, fail };
