/* tests_legal_pages.js — Checkpoint C1 contracts for the three legal/
 * informational pages (about, privacy, terms).
 *
 * Audit result: STATE B. The only structure privacy and terms share beyond the
 * B1 shell and standard HTML boilerplate is 3 trivial lines (<main class="prose">,
 * the "updated" paragraph, </main>). Extracting that would need a second body
 * compositor, 4+ new files and 15+ tests, and would risk mixing the two legal
 * namespaces — cost far exceeds a 95-byte reduction. So C1 changes NO production:
 * it protects the pages with contracts + golden + docs. about has a distinct
 * structure and purpose (branded, OG/Twitter) and does NOT share a template.
 *
 * checkLegalPages(siteDir) is the single official checker; the positive suite and
 * the negatives call it against a site tree and read { pass, fail, failures }.
 * Expected values come from engine/fixtures/pages-golden/legal-pages.json
 * (captured from the pre-C1 source, NOT generated by any compositor).
 *
 * Static file reads; no jsdom, no server. LF-only, no open handles.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function sha256(t) { return crypto.createHash('sha256').update(t, 'utf8').digest('hex'); }

function region(html, tag) {
  const m = html.match(new RegExp('<' + tag + '\\b[^>]*>([\\s\\S]*?)</' + tag + '>'));
  return m ? m[0] : null;
}
function allMatch(re, s) { const out = []; let m; while ((m = re.exec(s)) !== null) out.push(m[1]); return out; }

// The official C1 checker. Runs against a site tree; returns { pass, fail, failures }.
function checkLegalPages(siteDir) {
  let pass = 0, fail = 0;
  const failures = [];
  function check(name, cond) { if (cond) pass++; else { fail++; failures.push(name); } }

  const fixture = JSON.parse(fs.readFileSync(
    path.join(siteDir, 'engine', 'fixtures', 'pages-golden', 'legal-pages.json'), 'utf8'));
  const PAGES = ['about', 'privacy', 'terms'];

  const read = {};
  PAGES.forEach(function (p) { read[p] = fs.readFileSync(path.join(siteDir, p + '.html'), 'utf8'); });

  PAGES.forEach(function (p) {
    const html = read[p];
    const exp = fixture.pages[p];
    const head = region(html, 'head');
    const main = region(html, 'main');

    // Region hashes + byte lengths (removed section, changed heading, reordered
    // content, changed text all trip the main hash).
    check(p + ': <head> SHA-256 matches golden', head !== null && sha256(head) === exp.head_sha256);
    check(p + ': <head> byte length matches golden', head !== null && Buffer.byteLength(head, 'utf8') === exp.head_bytes);
    check(p + ': <main> SHA-256 matches golden', main !== null && sha256(main) === exp.main_sha256);
    check(p + ': <main> byte length matches golden', main !== null && Buffer.byteLength(main, 'utf8') === exp.main_bytes);

    // Canonical exact.
    const canon = (html.match(/rel="canonical"\s+href="([^"]+)"/) || [])[1];
    check(p + ': canonical matches golden (' + exp.canonical + ')', canon === exp.canonical);

    // i18n namespace + exact key set + no cross-namespace leakage.
    const nsMatch = (html.match(/init\('([^']+)'/) || [])[1];
    check(p + ': i18n init namespace is "' + exp.namespace + '"', nsMatch === exp.namespace);
    const keys = allMatch(/data-i18n="([^"]+)"/g, html).sort();
    check(p + ': data-i18n key set matches golden exactly',
      keys.length === exp.data_i18n_keys.length && keys.every(function (k, i) { return k === exp.data_i18n_keys[i]; }));

    // Heading order (tag:key) exact — catches a reordered or changed heading.
    const headings = [];
    const hre = /<(h[1-3])\b[^>]*data-i18n="([^"]+)"/g; let hm;
    while ((hm = hre.exec(main || '')) !== null) headings.push(hm[1] + ':' + hm[2]);
    check(p + ': heading order matches golden',
      headings.length === exp.heading_order.length && headings.every(function (h, i) { return h === exp.heading_order[i]; }));

    // Links, IDs, scripts, asset versions exact.
    const links = Array.from(new Set(allMatch(/<a\b[^>]*href="([^"]+)"/g, html))).sort();
    check(p + ': link set matches golden',
      links.length === exp.links.length && links.every(function (l, i) { return l === exp.links[i]; }));
    const ids = allMatch(/\bid="([^"]+)"/g, html).sort();
    check(p + ': id set matches golden',
      ids.length === exp.ids.length && ids.every(function (id, i) { return id === exp.ids[i]; }));
    // No duplicate IDs.
    const rawIds = allMatch(/\bid="([^"]+)"/g, html);
    check(p + ': no duplicate IDs', rawIds.length === new Set(rawIds).size);
    const scripts = Array.from(new Set(allMatch(/<script\b[^>]*src="([^"]+)"/g, html))).sort();
    check(p + ': script src set matches golden',
      scripts.length === exp.scripts.length && scripts.every(function (s, i) { return s === exp.scripts[i]; }));
    const versions = Array.from(new Set(allMatch(/(assets\/[a-z-]+\.(?:js|css)\?v=\d+)/g, html))).sort();
    check(p + ': asset versions match golden',
      versions.length === exp.asset_versions.length && versions.every(function (v, i) { return v === exp.asset_versions[i]; }));

    // Anchors resolve: every href="#id" points to an existing id on the page.
    const anchors = allMatch(/href="#([^"]+)"/g, html);
    anchors.forEach(function (a) {
      check(p + ': anchor #' + a + ' resolves to an existing id', rawIds.indexOf(a) !== -1);
    });

    // Isolation: no engine/Worker/grid/charts/exports; no CSS/HTML fetch; no
    // innerHTML building main; single stylesheet request (no added requests).
    check(p + ': does not load the engine', !/ENGINE_START|solveModel_|detectModel_/.test(html));
    check(p + ': does not create a Worker', !/new\s+Worker\s*\(/.test(html));
    check(p + ': does not carry grid/results/charts markup', !/id="grid"|class="[^"]*\b(gridwrap|receipt|plot|vs-row|exports)\b/.test(html));
    check(p + ': does not fetch content', !/fetch\s*\(/.test(html));
    check(p + ': does not build main via innerHTML', !/innerHTML/.test(html));
    check(p + ': loads exactly one stylesheet', (html.match(/<link[^>]*rel="stylesheet"/g) || []).length === 1);
  });

  // Legal content not mixed: privacy uses only pv*/updated keys, terms only
  // tm*/updated — no pv* key appears in terms and no tm* key in privacy.
  const pvKeys = allMatch(/data-i18n="([^"]+)"/g, read.privacy);
  const tmKeys = allMatch(/data-i18n="([^"]+)"/g, read.terms);
  check('privacy uses only pv*/shared keys (no tm* leakage)',
    pvKeys.every(function (k) { return k.indexOf('tm') !== 0; }));
  check('terms uses only tm*/shared keys (no pv* leakage)',
    tmKeys.every(function (k) { return k.indexOf('pv') !== 0; }));
  check('no privacy pv* key appears in terms',
    !tmKeys.some(function (k) { return k.indexOf('pv') === 0; }));
  check('no terms tm* key appears in privacy',
    !pvKeys.some(function (k) { return k.indexOf('tm') === 0; }));

  // about is distinct: its own namespace, and it does NOT use legal pv*/tm* keys.
  // Shared shell keys (e.g. the skip link, injected outside the page's own
  // content) are allowed alongside the about* namespace.
  const SHARED_SHELL_KEYS = ['skipToContent'];
  const abKeys = allMatch(/data-i18n="([^"]+)"/g, read.about);
  check('about uses its own about* namespace only',
    abKeys.every(function (k) { return k.indexOf('about') === 0 || SHARED_SHELL_KEYS.indexOf(k) !== -1; }));

  // No legal source fragment/partial exists to be published.
  check('no legal source partial directory', !fs.existsSync(path.join(siteDir, 'src', 'pages', 'legal')));

  return { pass: pass, fail: fail, failures: failures };
}

module.exports = { checkLegalPages: checkLegalPages };

if (require.main === module) {
  const siteDir = path.join(__dirname, '..');
  const r = checkLegalPages(siteDir);
  r.failures.forEach(function (f) { console.log('  FAIL:', f); });
  console.log('LEGAL PAGES TESTS  PASSED: ' + r.pass + '   FAILED: ' + r.fail);
  process.exit(r.fail ? 1 : 0);
}
