/* tests_css_golden.js — independent golden baseline for Plumline's CSS (B3).
 *
 * The expected values live in engine/fixtures/css-golden/shell-css-golden.json,
 * derived from the pre-B3 approved state — EXACT CSS fragments and SHA-256
 * hashes, NOT generated by any compositor at test time. This detects a removed
 * property, a changed value, a changed selector, a moved rule, a changed media
 * query, an altered specificity, and cross-variant leakage.
 *
 * The checker is exported (checkCssGolden) so the negative suite runs the SAME
 * validation against a mutated temp tree. Static file reads; no jsdom, no server.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function sha256(t) { return crypto.createHash('sha256').update(t, 'utf8').digest('hex'); }

// Pull the first inline <style> body out of a page.
function inlineStyle(html) {
  const m = html.match(/<style[^>]*>([\s\S]*?)<\/style>/);
  return m ? m[1] : null;
}

// Extract the exact `selector{...}` block for a simple (non-nested) selector.
function ruleBlock(css, selector) {
  const idx = css.indexOf(selector + '{');
  if (idx === -1) return null;
  const start = css.indexOf('{', idx);
  const end = css.indexOf('}', start);
  return end === -1 ? null : css.slice(idx, end + 1);
}

// Extract a full @media block (brace-balanced).
function mediaBlock(css, marker) {
  const idx = css.indexOf(marker);
  if (idx === -1) return null;
  let i = css.indexOf('{', idx), depth = 0, j = i;
  for (; j < css.length; j++) {
    if (css[j] === '{') depth++;
    else if (css[j] === '}') { depth--; if (depth === 0) break; }
  }
  return css.slice(idx, j + 1);
}

// The official CSS-golden checker. Runs against a site tree; returns
// { pass, fail, failures }. Both the positive suite and the negatives call it.
function checkCssGolden(siteDir) {
  let pass = 0, fail = 0;
  const failures = [];
  function check(name, cond) { if (cond) pass++; else { fail++; failures.push(name); } }

  const golden = JSON.parse(fs.readFileSync(
    path.join(siteDir, 'engine', 'fixtures', 'css-golden', 'shell-css-golden.json'), 'utf8'));
  const css = fs.readFileSync(path.join(siteDir, 'assets', 'plumline.css'), 'utf8');

  // 1. Whole-sheet hash (global safety net: any change anywhere trips this).
  check('plumline.css SHA-256 matches golden', sha256(css) === golden.plumline_css_sha256);
  check('plumline.css byte length matches golden', Buffer.byteLength(css, 'utf8') === golden.plumline_css_bytes);

  // 2. Exact shell fragments (pinpoint a removed property / changed value / changed selector).
  Object.keys(golden.shell_fragments).forEach(function (key) {
    const expected = golden.shell_fragments[key];
    let actual;
    if (key === 'reduced-motion') actual = mediaBlock(css, '@media(prefers-reduced-motion:reduce)');
    else actual = ruleBlock(css, key);
    check('shell fragment "' + key + '" is byte-identical to golden', actual === expected);
  });

  // 3. Structural counts (media queries, custom props, !important, keyframes, font-face).
  check('media query count matches golden', css.split('@media').length - 1 === golden.media_query_count);
  check('custom-property count matches golden',
    (css.match(/--[a-z0-9-]+:/g) || []).length === golden.custom_property_count);
  check('!important count matches golden',
    (css.match(/!important/g) || []).length === golden.important_count);
  check('@keyframes count matches golden', css.split('@keyframes').length - 1 === golden.keyframes_count);
  check('@font-face count matches golden', css.split('@font-face').length - 1 === golden.fontface_count);

  // 4. Every golden breakpoint is still present.
  golden.breakpoints.forEach(function (bp) {
    check('breakpoint ' + bp + ' present in plumline.css', css.indexOf(bp) !== -1);
  });

  // 5. Solver variant and Examples inline blocks unchanged (hash + bytes).
  const solverStyle = inlineStyle(fs.readFileSync(path.join(siteDir, 'solver.html'), 'utf8'));
  const examplesStyle = inlineStyle(fs.readFileSync(path.join(siteDir, 'examples.html'), 'utf8'));
  check('solver variant <style> matches golden hash', solverStyle !== null && sha256(solverStyle) === golden.solver_variant_style_sha256);
  check('solver variant <style> byte length matches golden', solverStyle !== null && Buffer.byteLength(solverStyle, 'utf8') === golden.solver_variant_style_bytes);
  check('examples <style> matches golden hash', examplesStyle !== null && sha256(examplesStyle) === golden.examples_style_sha256);
  check('examples <style> byte length matches golden', examplesStyle !== null && Buffer.byteLength(examplesStyle, 'utf8') === golden.examples_style_bytes);

  return { pass: pass, fail: fail, failures: failures };
}

module.exports = { checkCssGolden: checkCssGolden };

if (require.main === module) {
  const siteDir = path.join(__dirname, '..');
  const r = checkCssGolden(siteDir);
  r.failures.forEach(function (f) { console.log('  FAIL:', f); });
  console.log('CSS GOLDEN TESTS  PASSED: ' + r.pass + '   FAILED: ' + r.fail);
  process.exit(r.fail ? 1 : 0);
}
