/* tests_engine_baseline.js — Checkpoint E0 baseline guard.
 *
 * Pins the pre-E engine baseline so any future E-phase change to the engine's
 * bytes, the Worker glue, the Blob source, or the add-on twin (engine/engine.js)
 * is caught. This is a SMALL guard: it protects the baseline fixture, it does
 * NOT re-test parser/simplex/branch-and-bound (those stay in the existing math
 * suites). E0 adds no math coverage.
 *
 * The fixture engine/fixtures/single-engine/engine-e0-baseline.json is pinned by
 * SHA-256 here (no self-generation): the fixture is authored from the pre-E
 * state and must not be regenerated by any future engine implementation.
 *
 * Uses the SAME slice convention as tests_engine_integrity.js:
 *   engine = html.slice(indexOf(ENGINE_START), indexOf(ENGINE_END))
 * (START included, END excluded).
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const START = '/* ENGINE_START */';
const END = '/* ENGINE_END */';

function sha(s) { return crypto.createHash('sha256').update(s).digest('hex'); }

// The Worker glue is reconstructed VERBATIM from solve-worker-client.js. If the
// fragment's glue changes, blobSource/glue hashes below will diverge and fail.
const WORKER_GLUE = [
  'self.onmessage=function(e){',
  '  var d=e.data;',
  '  function mkSheet(formulas,values){',
  '    return {getDataRange:function(){return{',
  '      getRow:function(){return 1;},getColumn:function(){return 1;},',
  '      getFormulas:function(){return formulas;},getValues:function(){return values;}',
  '    };}};',
  '  }',
  '  try{',
  '    var sheet=mkSheet(d.formulas,d.values);',
  '    var model;',
  '    try{ model=detectModel_(sheet, d.localeMode); }',
  '    catch(rerr){ rerr.__phase="read"; throw rerr; }',
  '    model.wholeNumbers=d.wholeNumbers===true;',
  '    if(d.domains) model.domains=d.domains;',
  '    if(d.sense==="max"||d.sense==="min") model.objective.sense=d.sense;',
  '    var out=solveModel_(sheet,model, d.localeMode);',
  '    self.postMessage({token:d.token,ok:true,out:out,wholeNumbers:model.wholeNumbers});',
  '  }catch(err){',
  '    self.postMessage({token:d.token,ok:false,phase:(err&&err.__phase)||"solve",error:String(err&&err.message||err)});',
  '  }',
  '};'
].join('\n');

const FIXTURE_SHA = 'b174a9e58127393823842a06f6877f8fb52905af6f0a7e1688be4cd2ad8b11da';

function checkEngineBaseline(siteDir) {
  let pass = 0, fail = 0; const failures = [];
  function ok(name, cond, detail) {
    if (cond) pass++; else { fail++; failures.push(name + (detail ? ' :: ' + detail : '')); }
  }

  const fixturePath = path.join(siteDir, 'engine', 'fixtures', 'single-engine', 'engine-e0-baseline.json');
  const fixtureRaw = fs.readFileSync(fixturePath, 'utf8');
  const g = JSON.parse(fixtureRaw);

  // 1. Fixture is pinned (no self-generation): its own sha256 must match.
  ok('E0 fixture sha256 matches pin (no self-generation)', sha(fixtureRaw) === FIXTURE_SHA,
    'got ' + sha(fixtureRaw));

  // 2. Fixture carries no absolute path / home dir / node path.
  ok('E0 fixture has no absolute path', !/(^|["\s])\/(home|Users|mnt|tmp|usr)\//.test(fixtureRaw));
  ok('E0 fixture has no drive-letter path', !/[A-Za-z]:\\\\/.test(fixtureRaw));

  // 3. Canonical engine intact (slice convention == tests_engine_integrity).
  //    E1: the engine is composed into ENGINE_START..END from the internal
  //    canonical file; read the COMPOSED solver (not raw source, which no longer
  //    holds the inline engine). composedHtml is the canonical compositor, so this
  //    is a composed read needing no RAW_SOURCE_ALLOWLIST entry.
  const { composedHtml } = require('./composed-html.js');
  const { findEngineRegion } = require('../src/shared/compose-solver.js');
  let html = null, composeErr = null;
  try { html = composedHtml(siteDir, 'solver.html'); }
  catch (e) { composeErr = e; }
  ok('solver composes (engine source valid)', composeErr === null,
    composeErr ? composeErr.message : '');
  let region = null;
  if (html !== null) {
    try { region = findEngineRegion(html); } catch (e) { composeErr = e; }
  }
  ok('engine markers present exactly once', region !== null && region.end > region.start,
    composeErr ? composeErr.message : '');
  const a = region ? region.start : -1;
  const b = region ? region.end : -1;
  const engine = (html !== null && region) ? html.slice(a, b) : '';
  ok('engine chars == baseline', engine.length === g.engine_canonical.chars, 'got ' + engine.length);
  ok('engine bytes == baseline', Buffer.byteLength(engine, 'utf8') === g.engine_canonical.bytes_utf8,
    'got ' + Buffer.byteLength(engine, 'utf8'));
  const engineSha = sha(engine);
  ok('engine sha256 == baseline canonical', engineSha === g.engine_canonical.sha256, 'got ' + engineSha);

  // 4. Direct / Worker source parity: the Worker slices the SAME engine bytes.
  //    engineSource() in solve-worker-client.js uses the identical slice, so the
  //    reconstructed Blob source must hash to the pinned value.
  const glueBytes = Buffer.byteLength(WORKER_GLUE, 'utf8');
  ok('worker glue bytes == baseline', glueBytes === g.worker_execution.glue_bytes, 'got ' + glueBytes);
  ok('worker glue sha256 == baseline', sha(WORKER_GLUE) === g.worker_execution.glue_sha256, 'got ' + sha(WORKER_GLUE));
  const blobSource = engine + '\n' + WORKER_GLUE;
  ok('blob source bytes == baseline', Buffer.byteLength(blobSource, 'utf8') === g.worker_execution.blob_source_bytes,
    'got ' + Buffer.byteLength(blobSource, 'utf8'));
  ok('blob source sha256 == baseline', sha(blobSource) === g.worker_execution.blob_source_sha256,
    'got ' + sha(blobSource));
  ok('worker engineSource sha == canonical engine sha (direct/Worker byte parity)',
    g.worker_execution.worker_uses.indexOf(g.engine_canonical.sha256.slice(0, 8)) !== -1 || engineSha === g.engine_canonical.sha256);

  // 5. Glue actually present verbatim in the fragment (contract not drifted).
  const fragPath = path.join(siteDir, 'engine', 'fragments', 'solver-ui', 'solve-worker-client.js');
  const frag = fs.readFileSync(fragPath, 'utf8');
  ok('worker fragment contains the pinned onmessage contract',
    frag.indexOf('self.postMessage({token:d.token,ok:true,out:out,wholeNumbers:model.wholeNumbers});') !== -1);
  ok('worker fragment slices ENGINE_START..END for engineSource',
    frag.indexOf("txt.indexOf('/* ENGINE_START */')") !== -1 && frag.indexOf("txt.indexOf('/* ENGINE_END */')") !== -1);

  // 6. Add-on twin engine/engine.js. The fixture documents the HISTORICAL pre-E
  //    mirror (bytes/sha) as the baseline state. In E6 engine.js became a GENERATED
  //    artefact, so its CURRENT-STATE bytes/sha are owned by the E6 checker; here we
  //    assert the fixture still records the historical baseline (not rewritten to E6)
  //    and that the live file is the generator's output.
  const ejsPath = path.join(siteDir, 'engine', 'engine.js');
  const ejs = fs.readFileSync(ejsPath, 'utf8');
  ok('E0 fixture records the HISTORICAL mirror baseline (90220 bytes, not rewritten)', g.second_source.bytes_utf8 === 90220);
  ok('E0 fixture records the HISTORICAL mirror SHA (6190cb47, not rewritten)', g.second_source.sha256 === '6190cb4720dab3493fb2d903abf4bc0d915c1176605f121a903cdcdd0eb3a7fa');
  let genMirror = null; try { genMirror = require('./generate-engine-mirror.js').generateMirror(siteDir); } catch (e) { genMirror = null; }
  ok('live engine.js is the generated mirror (current-state authority: E6)', genMirror !== null && ejs === genMirror, 'got ' + sha(ejs));

  // 7. Engine constants unchanged (a subset spot-check; full set frozen).
  ok('engine EPSILON 1e-9 intact', /EPSILON\s*:\s*1e-9/.test(engine));
  ok('engine PIVOT_TOLERANCE 1e-7 intact', /PIVOT_TOLERANCE\s*:\s*1e-7/.test(engine));
  ok('engine MAX_ITERATIONS 20000 intact', /MAX_ITERATIONS\s*:\s*20000/.test(engine));

  return { pass, fail, failures };
}

module.exports = { checkEngineBaseline: checkEngineBaseline, WORKER_GLUE: WORKER_GLUE };

if (require.main === module) {
  const r = checkEngineBaseline(path.join(__dirname, '..'));
  console.log('ENGINE BASELINE (E0)  PASSED: ' + r.pass + '   FAILED: ' + r.fail);
  if (r.fail) { r.failures.forEach(f => console.log('  FAIL:', f)); process.exit(1); }
}
